# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class ANEFlowCoefficient(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, flowid: int=None, coefficient: float=None):
        """
        ANEFlowCoefficient - a model defined in Swagger

        :param flowid: The flowid of this ANEFlowCoefficient.
        :type flowid: int
        :param coefficient: The coefficient of this ANEFlowCoefficient.
        :type coefficient: float
        """
        self.swagger_types = {
            'flowid': int,
            'coefficient': float
        }

        self.attribute_map = {
            'flowid': 'flowid',
            'coefficient': 'coefficient'
        }

        self._flowid = flowid
        self._coefficient = coefficient

    @classmethod
    def from_dict(cls, dikt) -> 'ANEFlowCoefficient':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ANEFlowCoefficient of this ANEFlowCoefficient.
        :rtype: ANEFlowCoefficient
        """
        return deserialize_model(dikt, cls)

    @property
    def flowid(self) -> int:
        """
        Gets the flowid of this ANEFlowCoefficient.

        :return: The flowid of this ANEFlowCoefficient.
        :rtype: int
        """
        return self._flowid

    @flowid.setter
    def flowid(self, flowid: int):
        """
        Sets the flowid of this ANEFlowCoefficient.

        :param flowid: The flowid of this ANEFlowCoefficient.
        :type flowid: int
        """
        if flowid is None:
            raise ValueError("Invalid value for `flowid`, must not be `None`")

        self._flowid = flowid

    @property
    def coefficient(self) -> float:
        """
        Gets the coefficient of this ANEFlowCoefficient.

        :return: The coefficient of this ANEFlowCoefficient.
        :rtype: float
        """
        return self._coefficient

    @coefficient.setter
    def coefficient(self, coefficient: float):
        """
        Sets the coefficient of this ANEFlowCoefficient.

        :param coefficient: The coefficient of this ANEFlowCoefficient.
        :type coefficient: float
        """
        if coefficient is None:
            raise ValueError("Invalid value for `coefficient`, must not be `None`")

        self._coefficient = coefficient

