# coding: utf-8

from __future__ import absolute_import
from napps.snlab.unicorn_resource_discovery.models.error_response_meta import ErrorResponseMeta
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class ErrorResponse(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, meta: ErrorResponseMeta=None):
        """
        ErrorResponse - a model defined in Swagger

        :param meta: The meta of this ErrorResponse.
        :type meta: ErrorResponseMeta
        """
        self.swagger_types = {
            'meta': ErrorResponseMeta
        }

        self.attribute_map = {
            'meta': 'meta'
        }

        self._meta = meta

    @classmethod
    def from_dict(cls, dikt) -> 'ErrorResponse':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ErrorResponse of this ErrorResponse.
        :rtype: ErrorResponse
        """
        return deserialize_model(dikt, cls)

    @property
    def meta(self) -> ErrorResponseMeta:
        """
        Gets the meta of this ErrorResponse.

        :return: The meta of this ErrorResponse.
        :rtype: ErrorResponseMeta
        """
        return self._meta

    @meta.setter
    def meta(self, meta: ErrorResponseMeta):
        """
        Sets the meta of this ErrorResponse.

        :param meta: The meta of this ErrorResponse.
        :type meta: ErrorResponseMeta
        """

        self._meta = meta

