# coding: utf-8

from __future__ import absolute_import
from napps.snlab.unicorn_resource_discovery.models.ipv4_addr import Ipv4Addr
from napps.snlab.unicorn_resource_discovery.models.port_number import PortNumber
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class FlowSpec(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, dst_ip: Ipv4Addr=None, src_ip: Ipv4Addr=None, src_port: PortNumber=None, dst_port: PortNumber=None, protocol: str=None):
        """
        FlowSpec - a model defined in Swagger

        :param dst_ip: The dst_ip of this FlowSpec.
        :type dst_ip: Ipv4Addr
        :param src_ip: The src_ip of this FlowSpec.
        :type src_ip: Ipv4Addr
        :param src_port: The src_port of this FlowSpec.
        :type src_port: PortNumber
        :param dst_port: The dst_port of this FlowSpec.
        :type dst_port: PortNumber
        :param protocol: The protocol of this FlowSpec.
        :type protocol: str
        """
        self.swagger_types = {
            'dst_ip': Ipv4Addr,
            'src_ip': Ipv4Addr,
            'src_port': PortNumber,
            'dst_port': PortNumber,
            'protocol': str
        }

        self.attribute_map = {
            'dst_ip': 'dstIP',
            'src_ip': 'srcIP',
            'src_port': 'srcPort',
            'dst_port': 'dstPort',
            'protocol': 'protocol'
        }

        self._dst_ip = dst_ip
        self._src_ip = src_ip
        self._src_port = src_port
        self._dst_port = dst_port
        self._protocol = protocol

    @classmethod
    def from_dict(cls, dikt) -> 'FlowSpec':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The FlowSpec of this FlowSpec.
        :rtype: FlowSpec
        """
        return deserialize_model(dikt, cls)

    @property
    def dst_ip(self) -> Ipv4Addr:
        """
        Gets the dst_ip of this FlowSpec.

        :return: The dst_ip of this FlowSpec.
        :rtype: Ipv4Addr
        """
        return self._dst_ip

    @dst_ip.setter
    def dst_ip(self, dst_ip: Ipv4Addr):
        """
        Sets the dst_ip of this FlowSpec.

        :param dst_ip: The dst_ip of this FlowSpec.
        :type dst_ip: Ipv4Addr
        """
        if dst_ip is None:
            raise ValueError("Invalid value for `dst_ip`, must not be `None`")

        self._dst_ip = dst_ip

    @property
    def src_ip(self) -> Ipv4Addr:
        """
        Gets the src_ip of this FlowSpec.

        :return: The src_ip of this FlowSpec.
        :rtype: Ipv4Addr
        """
        return self._src_ip

    @src_ip.setter
    def src_ip(self, src_ip: Ipv4Addr):
        """
        Sets the src_ip of this FlowSpec.

        :param src_ip: The src_ip of this FlowSpec.
        :type src_ip: Ipv4Addr
        """

        self._src_ip = src_ip

    @property
    def src_port(self) -> PortNumber:
        """
        Gets the src_port of this FlowSpec.

        :return: The src_port of this FlowSpec.
        :rtype: PortNumber
        """
        return self._src_port

    @src_port.setter
    def src_port(self, src_port: PortNumber):
        """
        Sets the src_port of this FlowSpec.

        :param src_port: The src_port of this FlowSpec.
        :type src_port: PortNumber
        """

        self._src_port = src_port

    @property
    def dst_port(self) -> PortNumber:
        """
        Gets the dst_port of this FlowSpec.

        :return: The dst_port of this FlowSpec.
        :rtype: PortNumber
        """
        return self._dst_port

    @dst_port.setter
    def dst_port(self, dst_port: PortNumber):
        """
        Sets the dst_port of this FlowSpec.

        :param dst_port: The dst_port of this FlowSpec.
        :type dst_port: PortNumber
        """

        self._dst_port = dst_port

    @property
    def protocol(self) -> str:
        """
        Gets the protocol of this FlowSpec.

        :return: The protocol of this FlowSpec.
        :rtype: str
        """
        return self._protocol

    @protocol.setter
    def protocol(self, protocol: str):
        """
        Sets the protocol of this FlowSpec.

        :param protocol: The protocol of this FlowSpec.
        :type protocol: str
        """

        self._protocol = protocol

