# coding: utf-8

from __future__ import absolute_import
from napps.snlab.unicorn_resource_discovery.models.query_desc import QueryDesc
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class QueryRequests(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self):
        """
        QueryRequests - a model defined in Swagger

        """
        self.swagger_types = {
            
        }

        self.attribute_map = {
            
        }


    @classmethod
    def from_dict(cls, dikt) -> 'QueryRequests':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The QueryRequests of this QueryRequests.
        :rtype: QueryRequests
        """
        return deserialize_model(dikt, cls)
