# coding: utf-8

from __future__ import absolute_import
from swagger_server.models.error_meta import ErrorMeta
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Error(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, meta: ErrorMeta=None):
        """
        Error - a model defined in Swagger

        :param meta: The meta of this Error.
        :type meta: ErrorMeta
        """
        self.swagger_types = {
            'meta': ErrorMeta
        }

        self.attribute_map = {
            'meta': 'meta'
        }

        self._meta = meta

    @classmethod
    def from_dict(cls, dikt) -> 'Error':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Error of this Error.
        :rtype: Error
        """
        return deserialize_model(dikt, cls)

    @property
    def meta(self) -> ErrorMeta:
        """
        Gets the meta of this Error.

        :return: The meta of this Error.
        :rtype: ErrorMeta
        """
        return self._meta

    @meta.setter
    def meta(self, meta: ErrorMeta):
        """
        Sets the meta of this Error.

        :param meta: The meta of this Error.
        :type meta: ErrorMeta
        """

        self._meta = meta

